services:
  app:
    build:
      context: .
      target: runtime
    image: production-api:latest
    container_name: production-api
    env_file:
      - .env.production
    environment:
      PORT: ${PORT:-4001}
      # DATABASE_URL must point to your Neon Cloud DB (postgres://...neon.tech...)
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4001:4001"
    restart: unless-stopped
